# Generated by Django 3.2.3 on 2021-05-26 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'likeproducts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='상품 이름')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드')),
                ('sale_price', models.FloatField(verbose_name='판매가')),
                ('price', models.FloatField(verbose_name='원가')),
                ('discount_rate', models.IntegerField(verbose_name='할인율')),
                ('url', models.URLField(max_length=2000, verbose_name='상품 url')),
                ('thumnail', models.URLField(max_length=2000, verbose_name='대표 이미지')),
                ('category', models.CharField(default='clothes', max_length=200, verbose_name='카테고리')),
                ('color', models.CharField(max_length=20, verbose_name='색상')),
                ('likeProduct', models.ManyToManyField(related_name='like_product', through='products.LikeProduct', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '상품',
                'db_table': 'Product',
            },
        ),
        migrations.AddField(
            model_name='likeproduct',
            name='products',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_product', to='products.product'),
        ),
        migrations.AddField(
            model_name='likeproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
