# Generated by Django 3.2.3 on 2021-05-27 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20210528_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeproduct',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='like_product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='likeproduct',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
