# Generated by Django 3.2.3 on 2021-06-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_auto_20210602_1418'),
        ('user', '0004_auto_20210603_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='styles',
        ),
        migrations.AddField(
            model_name='user',
            name='styles',
            field=models.ManyToManyField(blank=True, db_column='style_id', default='', null=True, related_name='style', to='style.Style'),
        ),
    ]
