# Generated by Django 3.2.3 on 2021-06-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_styles'),
        ('user', '0006_auto_20210609_1402'),
    ]

    operations = [
    ]
