# Generated by Django 3.2.3 on 2021-06-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='style',
            name='user_id',
        ),
        migrations.AddField(
            model_name='style',
            name='style_img',
            field=models.ImageField(default='null', upload_to='%Y/%m/%d', verbose_name='image_url'),
        ),
    ]
