# Generated by Django 3.2.3 on 2021-05-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawl_data',
            name='category',
            field=models.CharField(default='clothes', max_length=200),
        ),
    ]
