# Generated by Django 3.2.3 on 2021-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_crawl_data_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='상품 이름')),
                ('brand', models.CharField(max_length=30, verbose_name='브랜드')),
                ('sale_price', models.FloatField(verbose_name='판매가')),
                ('price', models.FloatField(verbose_name='원가')),
                ('discount_rate', models.IntegerField(verbose_name='할인율')),
                ('url', models.URLField(max_length=2000, verbose_name='상품 url')),
                ('thumnail', models.URLField(max_length=2000, verbose_name='대표 이미지')),
                ('category', models.CharField(default='clothes', max_length=200, verbose_name='카테고리')),
                ('color', models.CharField(max_length=20, verbose_name='색상')),
                ('star', models.BooleanField(default='false', verbose_name='찜 유무')),
            ],
            options={
                'verbose_name': '상품',
                'db_table': 'Product',
            },
        ),
        migrations.DeleteModel(
            name='Crawl_data',
        ),
    ]
