# Generated by Django 3.2.3 on 2021-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_auto_20210522_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='브랜드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='상품 이름'),
        ),
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.BooleanField(default=False, verbose_name='찜 유무'),
        ),
    ]
